spring:
  application:
    name: zzzpot
  profiles:
    default: local
  datasource:
    url: ${jdbc:${POSTGRES_USER}:${POSTGRES_PASSWORD}//localhost:5432/${POSTGRES_DB:zzzpot}}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
